services:
  postgres:
    image: postgres:17
    container_name: financialoverview-db

    environment:
      POSTGRES_DB: financialoverview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - financialoverview_data:/var/lib/postgresql/data

volumes:
  financialoverview_data: